<?php

/**
 * resources/templates/etc/appserver/appserver.xml.phtml
 *
 * PHP version 5
 *
 * @category   Server
 * @package    Appserver
 * @subpackage Meta
 * @author     Tim Wagner <tw@appserver.io>
 * @author     Bernhard Wick <bw@appserver.io>
 * @author     Johann Zelger <jz@appserver.io>
 * @copyright  2014 TechDivision GmbH <info@appserver.io>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       http://www.appserver.io
 */

use AppserverIo\Appserver\Meta\Composer\Script\Setup;
use AppserverIo\Appserver\Meta\Composer\Script\SetupKeys;

?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL ?>
<appserver xmlns="http://www.appserver.io/appserver"  xmlns:xi="http://www.w3.org/2001/XInclude">

    <params>
        <param name="user" type="string"><?php echo Setup::getValue(SetupKeys::USER) ?></param>
        <param name="group" type="string"><?php echo Setup::getValue(SetupKeys::GROUP) ?></param>
        <param name="umask" type="string"><?php echo Setup::getValue(SetupKeys::UMASK) ?></param>
    </params>

    <!--
     ! You might add optional configuration for implicitly configured components here.
     !
     ! http://appserver.io/get-started/documentation/configuration.html#optional-configuration
     -->

    <containers>

        <container
                name="combined-appserver"
                type="AppserverIo\Appserver\Core\GenericContainer">

            <description>
                <![CDATA[This is an example of a webserver container that handles http requests in common way]]>
            </description>

            <deployment type="AppserverIo\Appserver\Core\GenericDeployment" />

            <host name="localhost" appBase="/webapps" />

            <servers>

                <!--
                 | To distribute componenents like SLSBs across a network, you've to configure separate server for
                 | the Persistence-Container.
                 |
                 | http://appserver.io/get-started/documentation/configuration.html#persistence-container-(remote)
                 |-->

                <server
                        name="message-queue"
                        type="\AppserverIo\Server\Servers\MultiThreadedServer"
                        worker="\AppserverIo\Server\Workers\ThreadWorker"
                        socket="\AppserverIo\Server\Sockets\StreamSocket"
                        requestContext="\AppserverIo\Server\Contexts\RequestContext"
                        serverContext="\AppserverIo\Server\Contexts\ServerContext"
                        loggerName="System">

                    <params>
                        <param name="admin" type="string"><?php echo Setup::getValue(SetupKeys::ADMIN_EMAIL) ?></param>
                        <param name="transport" type="string">tcp</param>
                        <param name="address" type="string"><?php echo Setup::getValue(SetupKeys::CONTAINER_MESSAGE_QUEUE_HOST) ?></param>
                        <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_MESSAGE_QUEUE_PORT) ?></param>
                        <param name="workerNumber" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_MESSAGE_QUEUE_WORKER_NUMBER) ?></param>
                        <param name="workerAcceptMin" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_SERVER_WORKER_ACCEPT_MIN) ?></param>
                        <param name="workerAcceptMax" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_SERVER_WORKER_ACCEPT_MAX) ?></param>
                        <param name="documentRoot" type="string">webapps</param>
                        <param name="directoryIndex" type="string">index.mq</param>
                        <param name="keepAliveMax" type="integer">64</param>
                        <param name="keepAliveTimeout" type="integer">5</param>
                        <param name="errorsPageTemplatePath" type="string">var/www/errors/error.phtml</param>
                    </params>

                    <environmentVariables>
                        <environmentVariable condition="" definition="LOGGER_ACCESS=Access" />
                    </environmentVariables>

                    <connectionHandlers>
                        <connectionHandler type="\AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler" />
                    </connectionHandlers>

                    <accesses>
                        <!-- per default allow everything -->
                        <access type="allow">
                            <params>
                                <param name="X_REQUEST_URI" type="string">.*</param>
                            </params>
                        </access>
                    </accesses>

                    <modules>
                        <!-- REQUEST_POST hook -->
                        <module type="\AppserverIo\WebServer\Modules\AuthenticationModule"/>
                        <module type="\AppserverIo\WebServer\Modules\VirtualHostModule"/>
                        <module type="\AppserverIo\WebServer\Modules\EnvironmentVariableModule" />
                        <module type="\AppserverIo\WebServer\Modules\RewriteModule"/>
                        <module type="\AppserverIo\WebServer\Modules\DirectoryModule"/>
                        <module type="\AppserverIo\WebServer\Modules\AccessModule"/>
                        <module type="\AppserverIo\WebServer\Modules\CoreModule"/>
                        <module type="\AppserverIo\Appserver\MessageQueue\MessageQueueModule" />
                        <!-- RESPONSE_PRE hook -->
                        <module type="\AppserverIo\WebServer\Modules\DeflateModule"/>
                        <!-- RESPONSE_POST hook -->
                        <module type="\AppserverIo\Appserver\Core\Modules\ProfileModule"/>
                    </modules>

                    <fileHandlers>
                        <fileHandler name="message-queue" extension=".mq" />
                    </fileHandlers>

                </server>

                <server
                        name="http"
                        type="\AppserverIo\Server\Servers\MultiThreadedServer"
                        worker="\AppserverIo\Server\Workers\ThreadWorker"
                        socket="\AppserverIo\Server\Sockets\StreamSocket"
                        serverContext="\AppserverIo\Server\Contexts\ServerContext"
                        requestContext="\AppserverIo\Server\Contexts\RequestContext"
                        loggerName="System">
                    <params>
                        <param name="admin" type="string"><?php echo Setup::getValue(SetupKeys::ADMIN_EMAIL) ?></param>
                        <param name="transport" type="string">tcp</param>
                        <param name="address" type="string"><?php echo Setup::getValue(SetupKeys::CONTAINER_HTTP_HOST) ?></param>
                        <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_HTTP_PORT) ?></param>
                        <param name="workerNumber" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_HTTP_WORKER_NUMBER) ?></param>
                        <param name="workerAcceptMin" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_SERVER_WORKER_ACCEPT_MIN) ?></param>
                        <param name="workerAcceptMax" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_SERVER_WORKER_ACCEPT_MAX) ?></param>
                        <param name="documentRoot" type="string">webapps</param>
                        <param name="directoryIndex" type="string">index.do index.php index.html index.htm</param>
                        <param name="keepAliveMax" type="integer">64</param>
                        <param name="keepAliveTimeout" type="integer">5</param>
                        <param name="errorsPageTemplatePath" type="string">var/www/errors/error.phtml</param>
                        <param name="welcomePageTemplatePath" type="string">var/www/errors/welcome.phtml</param>
                    </params>

                    <environmentVariables>
                        <environmentVariable condition="" definition="LOGGER_ACCESS=Access" />
                    </environmentVariables>

                    <connectionHandlers>
                        <connectionHandler type="\AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler" />
                    </connectionHandlers>

                    <!-- An example for basic or digest auth for the server -->
                    <!--
                    <authentications>
                        <authentication uri="^\/auth\/basic\/.*">
                            <params>
                                <param name="type" type="string">\AppserverIo\Http\Authentication\BasicAuthentication</param>
                                <param name="realm" type="string">PhpWebServer Basic Authentication System</param>
                                <param name="file" type="string">var/www/auth/basic/.htpasswd</param>
                            </params>
                        </authentication>
                        <authentication uri="^\/auth\/digest\/.*">
                            <params>
                                <param name="type" type="string">\AppserverIo\Http\Authentication\DigestAuthentication</param>
                                <param name="realm" type="string">appserver.io Digest Authentication System</param>
                                <param name="adapter-type" type="string">htdigest</param>
                                <param name="file" type="string">var/www/auth/digest/.htpasswd</param>
                            </params>
                        </authentication>
                    </authentications>
                    -->

                    <accesses>
                        <!-- per default allow everything -->
                        <access type="allow">
                            <params>
                                <param name="X_REQUEST_URI" type="string">.*</param>
                            </params>
                        </access>
                    </accesses>

                    <!-- include of virtual host configurations -->
                    <xi:include href="conf.d/virtual-hosts.xml"/>

                    <modules>
                        <!-- REQUEST_POST hook -->
                        <module type="\AppserverIo\WebServer\Modules\VirtualHostModule"/>
                        <module type="\AppserverIo\WebServer\Modules\AuthenticationModule"/>
                        <module type="\AppserverIo\WebServer\Modules\EnvironmentVariableModule" />
                        <module type="\AppserverIo\WebServer\Modules\RewriteModule"/>
                        <module type="\AppserverIo\WebServer\Modules\DirectoryModule"/>
                        <module type="\AppserverIo\WebServer\Modules\AccessModule"/>
                        <module type="\AppserverIo\WebServer\Modules\CoreModule"/>
                        <module type="\AppserverIo\WebServer\Modules\PhpModule"/>
                        <module type="\AppserverIo\WebServer\Modules\FastCgiModule"/>
                        <module type="\AppserverIo\Appserver\ServletEngine\ServletEngine" />
                        <!-- RESPONSE_PRE hook -->
                        <module type="\AppserverIo\WebServer\Modules\DeflateModule"/>
                        <!-- RESPONSE_POST hook -->
                        <module type="\AppserverIo\Appserver\Core\Modules\ProfileModule"/>
                    </modules>

                    <fileHandlers>
                        <fileHandler name="fastcgi" extension=".php">
                            <params>
                                <param name="host" type="string"><?php echo Setup::getValue(SetupKeys::PHP_FPM_HOST) ?></param>
                                <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::PHP_FPM_PORT) ?></param>
                            </params>
                        </fileHandler>
                        <fileHandler name="fastcgi" extension=".phtml">
                            <params>
                                <param name="host" type="string"><?php echo Setup::getValue(SetupKeys::PHP_FPM_HOST) ?></param>
                                <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::PHP_FPM_PORT) ?></param>
                            </params>
                        </fileHandler>
                        <fileHandler name="servlet" extension=".do" />
                    </fileHandlers>

                </server>

                <server
                        name="https"
                        type="\AppserverIo\Server\Servers\MultiThreadedServer"
                        worker="\AppserverIo\Server\Workers\ThreadWorker"
                        socket="\AppserverIo\Server\Sockets\StreamSocket"
                        serverContext="\AppserverIo\Server\Contexts\ServerContext"
                        requestContext="\AppserverIo\Server\Contexts\RequestContext"
                        loggerName="System">
                    <params>
                        <param name="admin" type="string"><?php echo Setup::getValue(SetupKeys::ADMIN_EMAIL) ?></param>
                        <param name="workerNumber" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_HTTPS_WORKER_NUMBER) ?></param>
                        <param name="workerAcceptMin" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_SERVER_WORKER_ACCEPT_MIN) ?></param>
                        <param name="workerAcceptMax" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_SERVER_WORKER_ACCEPT_MAX) ?></param>
                        <param name="transport" type="string">ssl</param>
                        <param name="address" type="string"><?php echo Setup::getValue(SetupKeys::CONTAINER_HTTPS_HOST) ?></param>
                        <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::CONTAINER_HTTPS_PORT) ?></param>
                        <param name="certPath" type="string">etc/appserver/server.pem</param>
                        <param name="passphrase" type="string"></param>
                        <param name="documentRoot" type="string">webapps</param>
                        <param name="directoryIndex" type="string">index.do index.php index.html index.htm</param>
                        <param name="keepAliveMax" type="integer">64</param>
                        <param name="keepAliveTimeout" type="integer">5</param>
                        <param name="errorsPageTemplatePath" type="string">var/www/errors/error.phtml</param>
                        <param name="welcomePageTemplatePath" type="string">var/www/errors/welcome.phtml</param>
                    </params>

                    <environmentVariables>
                        <environmentVariable condition="" definition="LOGGER_ACCESS=Access" />
                    </environmentVariables>

                    <connectionHandlers>
                        <connectionHandler type="\AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler" />
                    </connectionHandlers>

                    <!-- An example for basic or digest auth for the server -->
                    <!--
                    <authentications>
                        <authentication uri="^\/auth\/basic\/.*">
                            <params>
                                <param name="type" type="string">\AppserverIo\Http\Authentication\BasicAuthentication</param>
                                <param name="realm" type="string">PhpWebServer Basic Authentication System</param>
                                <param name="file" type="string">var/www/auth/basic/.htpasswd</param>
                            </params>
                        </authentication>
                        <authentication uri="^\/auth\/digest\/.*">
                            <params>
                                <param name="type" type="string">\AppserverIo\Http\Authentication\DigestAuthentication</param>
                                <param name="realm" type="string">appserver.io Digest Authentication System</param>
                                <param name="file" type="string">var/www/auth/digest/.htpasswd</param>
                            </params>
                        </authentication>
                    </authentications>
                    -->

                    <accesses>
                        <!-- per default allow everything -->
                        <access type="allow">
                            <params>
                                <param name="X_REQUEST_URI" type="string">.*</param>
                            </params>
                        </access>
                    </accesses>

                    <!-- include of virtual host configurations -->
                    <xi:include href="conf.d/virtual-hosts.xml"/>

                    <modules>
                        <!-- REQUEST_POST hook -->
                        <module type="\AppserverIo\WebServer\Modules\VirtualHostModule"/>
                        <module type="\AppserverIo\WebServer\Modules\AuthenticationModule"/>
                        <module type="\AppserverIo\WebServer\Modules\EnvironmentVariableModule" />
                        <module type="\AppserverIo\WebServer\Modules\RewriteModule"/>
                        <module type="\AppserverIo\WebServer\Modules\DirectoryModule"/>
                        <module type="\AppserverIo\WebServer\Modules\AccessModule"/>
                        <module type="\AppserverIo\WebServer\Modules\CoreModule"/>
                        <module type="\AppserverIo\WebServer\Modules\PhpModule"/>
                        <module type="\AppserverIo\WebServer\Modules\FastCgiModule"/>
                        <module type="\AppserverIo\Appserver\ServletEngine\ServletEngine" />
                        <!-- RESPONSE_PRE hook -->
                        <module type="\AppserverIo\WebServer\Modules\DeflateModule"/>
                        <!-- RESPONSE_POST hook -->
                        <module type="\AppserverIo\Appserver\Core\Modules\ProfileModule"/>
                    </modules>

                    <fileHandlers>
                        <fileHandler name="fastcgi" extension=".php">
                            <params>
                                <param name="host" type="string"><?php echo Setup::getValue(SetupKeys::PHP_FPM_HOST) ?></param>
                                <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::PHP_FPM_PORT) ?></param>
                            </params>
                        </fileHandler>
                        <fileHandler name="fastcgi" extension=".phtml">
                            <params>
                                <param name="host" type="string"><?php echo Setup::getValue(SetupKeys::PHP_FPM_HOST) ?></param>
                                <param name="port" type="integer"><?php echo Setup::getValue(SetupKeys::PHP_FPM_PORT) ?></param>
                            </params>
                        </fileHandler>
                        <fileHandler name="servlet" extension=".do" />
                    </fileHandlers>

                </server>

            </servers>
        </container>

    </containers>

</appserver>
