<?xml version="1.0" encoding="UTF-8"?>
<appserver xmlns="http://www.appserver.io/appserver"  xmlns:xi="http://www.w3.org/2001/XInclude">

    <params>
        <param name="user" type="string">_www</param>
        <param name="group" type="string">staff</param>
        <param name="umask" type="string">0002</param>
        <param name="allowApplicationConfiguration" type="boolean">true</param>
    </params>

    <!--
     ! Customize this to fit your needs ragarding log information. The logLevel attribute can be one
     ! of https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#5-psrlogloglevel.
     -->

    <loggers>
        <logger channelName="system" name="System" type="\AppserverIo\Logger\Logger">
            <handlers>
                <handler type="\AppserverIo\Logger\Handlers\CustomFileHandler">
                    <formatter type="\AppserverIo\Logger\Formatters\StandardFormatter"/>
                    <params>
                        <param name="logFile" type="string">var/log/appserver-errors.log</param>
                        <param name="logLevel" type="string">info</param>
                    </params>
                </handler>
            </handlers>
        </logger>
        <logger channelName="access" name="Access" type="\AppserverIo\Logger\Logger">
            <handlers>
                <handler type="\AppserverIo\Logger\Handlers\CustomFileHandler">
                    <formatter type="\AppserverIo\Logger\Formatters\StandardFormatter">
                        <params>
                            <param name="format" type="string">%4$s</param>
                        </params>
                    </formatter>
                    <params>
                        <param name="logFile" type="string">var/log/appserver-access.log</param>
                        <param name="logLevel" type="string">info</param>
                    </params>
                </handler>
            </handlers>
        </logger>
    </loggers>

    <containers>

        <container
                name="combined-appserver"
                type="AppserverIo\Appserver\Core\GenericContainer"
                factory="AppserverIo\Appserver\Core\GenericContainerFactory">

            <description>
                <![CDATA[This is an example of a webserver container that handles http requests in common way]]>
            </description>

            <deployment type="AppserverIo\Appserver\Core\GenericDeployment" />

            <host name="localhost" appBase="webapps" deployBase="deploy" tmpBase="var/tmp/localhost" />

            <servers>

                <server
                        name="message-queue"
                        type="\AppserverIo\Server\Servers\MultiThreadedServer"
                        worker="\AppserverIo\Server\Workers\ThreadWorker"
                        socket="\AppserverIo\Server\Sockets\StreamSocket"
                        requestContext="\AppserverIo\Server\Contexts\RequestContext"
                        serverContext="\AppserverIo\Appserver\Server\Contexts\StandardServerContext"
                        streamContext="\AppserverIo\Server\Contexts\StreamContext"
                        loggerName="System">

                    <params>
                        <param name="admin" type="string">info@appserver.io</param>
                        <param name="transport" type="string">tcp</param>
                        <param name="address" type="string">127.0.0.1</param>
                        <param name="port" type="integer">8587</param>
                        <param name="workerNumber" type="integer">4</param>
                        <param name="workerAcceptMin" type="integer">3</param>
                        <param name="workerAcceptMax" type="integer">8</param>
                        <param name="documentRoot" type="string">webapps</param>
                        <param name="directoryIndex" type="string">index.mq</param>
                        <param name="keepAliveMax" type="integer">64</param>
                        <param name="keepAliveTimeout" type="integer">5</param>
                        <param name="errorsPageTemplatePath" type="string">resources/templates/www/error.phtml</param>
                    </params>

                    <environmentVariables>
                        <environmentVariable condition="" definition="LOGGER_ACCESS=Access" />
                    </environmentVariables>

                    <connectionHandlers>
                        <connectionHandler type="\AppserverIo\Appserver\MessageQueue\ConnectionHandlers\AmqpConnectionHandler" />
                    </connectionHandlers>

                    <accesses>
                        <!-- per default allow everything -->
                        <access type="allow">
                            <params>
                                <param name="X_REQUEST_URI" type="string">.*</param>
                            </params>
                        </access>
                    </accesses>

                    <modules>
                        <!-- REQUEST_POST hook -->
                        <module type="\AppserverIo\WebServer\Modules\AuthenticationModule"/>
                        <module type="\AppserverIo\WebServer\Modules\VirtualHostModule"/>
                        <module type="\AppserverIo\WebServer\Modules\EnvironmentVariableModule" />
                        <module type="\AppserverIo\WebServer\Modules\RewriteModule"/>
                        <module type="\AppserverIo\WebServer\Modules\DirectoryModule"/>
                        <module type="\AppserverIo\WebServer\Modules\AccessModule"/>
                        <module type="\AppserverIo\WebServer\Modules\CoreModule"/>
                        <module type="\AppserverIo\Appserver\MessageQueue\MessageQueueModule" />
                        <!-- RESPONSE_PRE hook -->
                        <module type="\AppserverIo\WebServer\Modules\DeflateModule"/>
                    </modules>

                    <fileHandlers>
                        <fileHandler name="message-queue" extension=".mq" />
                    </fileHandlers>

                </server>

            </servers>
        </container>

    </containers>

</appserver>
