<?php

/**
 * resources/templates/var/tmp/opcache-blacklist.txt.phtml
 *
 * PHP version 5
 *
 * @category   Server
 * @package    Appserver
 * @subpackage Meta
 * @author     Tim Wagner <tw@techdivision.com>
 * @copyright  2014 TechDivision GmbH <info@techdivision.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       http://www.appserver.io
 */

use AppserverIo\Appserver\Meta\Composer\Script\Setup;
use AppserverIo\Appserver\Meta\Composer\Script\SetupKeys;

?>
; Blacklists all PHP files in the webapps/demo directory and all subdirectories
;<?php echo Setup::getValue(SetupKeys::INSTALL_DIR) ?>/webapps**/*.php

; Blacklists all flow eel expression codes
<?php echo Setup::getValue(SetupKeys::INSTALL_DIR) ?>/webapps/**/Eel_Expression_Code/*.php

; Override core functions removed
<?php echo Setup::getValue(SetupKeys::INSTALL_DIR) ?>/var/scripts/core_functions.php